---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/secrethub --version
    register: secrethub_test_output
  - name: secrethub --version
    debug:
      msg: '{{ secrethub_test_output.stdout }}'
