---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for secrethub install in {{ secrethub_install_dir }}...
  become: true
  stat:
    path: '{{ secrethub_install_dir }}'
  changed_when: false
  register: secrethub_binary
- when: not secrethub_binary.stat.exists
  block:
    - name: downloading {{ secrethub_url }} to {{ secrethub_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ secrethub_url }}'
        dest: '{{ secrethub_tmp_archive }}'
        mode: 0644
        checksum: '{{ secrethub_checksum }}'
    - name: mkdir {{ secrethub_install_dir }}...
      become: true
      become_user: root
      file:
        path: '{{ secrethub_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchiving {{ secrethub_tmp_archive }} to {{ secrethub_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ secrethub_tmp_archive }}'
        dest: '{{ secrethub_install_dir }}'
        creates: '{{ secrethub_exe }}'
  always:
    - name: rm {{ secrethub_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ secrethub_tmp_archive }}'
        state: absent
- name: linking {{ secrethub_link }} to {{ secrethub_exe }}
  become: true
  become_user: root
  file:
    src: '{{ secrethub_exe }}'
    dest: '{{ secrethub_link }}'
    state: link
